DROP SEQUENCE XX_ETW.XX_DISL_CAR_NOTIF_GU2d_SEQ;
CREATE SEQUENCE XX_ETW.XX_DISL_CAR_NOTIF_GU2d_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
DROP SEQUENCE XX_ETW.XX_DISL_NOTIFICATIONS_GU2D_SEQ;

CREATE SEQUENCE XX_ETW.XX_DISL_NOTIFICATIONS_GU2D_SEQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP TABLE XX_ETW.XX_DISL_NOTIFICATIONS_GU_2D CASCADE CONSTRAINTS;

CREATE TABLE XX_ETW.XX_DISL_NOTIFICATIONS_GU_2D
(
  NOTIFICATION_ID  NUMBER,
  NOT_NUMBER       VARCHAR2(200 BYTE),
  NOT_TIME         DATE,
  NOT_PERSON_FROM  NUMBER,
  NOT_COMMENT      VARCHAR2(1000 BYTE),
  NOT_TIME_FACT    DATE,
  NOT_PERSON_TO    VARCHAR2(500 BYTE),
  CREATED_BY       NUMBER,
  CREATED_DATE     DATE,
  CRG_PCALID       NUMBER
)
TABLESPACE XX_ETWD
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON COLUMN XX_ETW.XX_DISL_NOTIFICATIONS_GU_2D.CRG_PCALID IS 'add 11.11.2024 по наряду 0000068904 
Номер договора экспл.путей';


CREATE UNIQUE INDEX XX_ETW.XX_DISL_NOTIFICATIONS_GU_2D_PK ON XX_ETW.XX_DISL_NOTIFICATIONS_GU_2D
(NOTIFICATION_ID)
LOGGING
TABLESPACE XX_ETWD
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE XX_ETW.XX_DISL_NOTIFICATIONS_GU_2D ADD (
  CONSTRAINT XX_DISL_NOTIFICATIONS_GU_2D_PK
  PRIMARY KEY
  (NOTIFICATION_ID)
  USING INDEX XX_ETW.XX_DISL_NOTIFICATIONS_GU_2D_PK
  ENABLE VALIDATE);

DROP TABLE XX_ETW.XX_DISL_CAR_NOTIF_GU_2D CASCADE CONSTRAINTS;

CREATE TABLE XX_ETW.XX_DISL_CAR_NOTIF_GU_2D
(
  PK_ID            NUMBER,
  ROUND_ID         NUMBER,
  NOTIFICATION_ID  NUMBER,
  LAST_RECORD      VARCHAR2(1 BYTE)
)
TABLESPACE XX_ETWD
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE INDEX XX_ETW.XX_DISL_CAR_NOTIF_GU_2D_I1 ON XX_ETW.XX_DISL_CAR_NOTIF_GU_2D
(ROUND_ID)
LOGGING
TABLESPACE XX_ETWD
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX XX_ETW.XX_DISL_CAR_NOTIF_GU_2D_I2 ON XX_ETW.XX_DISL_CAR_NOTIF_GU_2D
(NOTIFICATION_ID)
LOGGING
TABLESPACE XX_ETWD
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


DROP TABLE XX_ETW.XX_DISL_NOTIFICATION_GU2d_LINK CASCADE CONSTRAINTS;

CREATE TABLE XX_ETW.XX_DISL_NOTIFICATION_GU2d_LINK
(
  NOTIFICATION_ID  NUMBER,
  FRONT_END_ID     NUMBER
)