CREATE OR REPLACE VIEW XX_ETW.XX_DISL_UNION_NAME_V AS
SELECT TO_CHAR(STATION_ID) ID,
       'station' TYPE,
       NAME,
       CAST(NULL AS VARCHAR2(100)) DISABLED
  FROM XX_ETW.XX_DISL_STATIONS
UNION ALL
SELECT TO_CHAR(RAILWAY_ID) ID,
       'railway' TYPE,
       RAILWAY_NUMBER NAME,
       DISABLED
  FROM XX_ETW.XX_DISL_RAILWAYS
UNION ALL
SELECT TO_CHAR(AREA_ID) ID,
       'area' TYPE,
       NAME,
       CAST(NULL AS VARCHAR2(100)) DISABLED
  FROM XX_ETW.XX_DISL_AREAS;

CREATE OR REPLACE VIEW XX_ETW.XX_DISL_FREIGHT_LIST_V AS
SELECT *
  FROM XX_ETW.XX_DISL_FREIGHT_LIST;

CREATE OR REPLACE VIEW XX_ETW.XX_DISL_SCALES_TYPE_V AS
SELECT ROW_NUMBER() OVER (ORDER BY TYPE) ID,
       TYPE NAME
  FROM (
        SELECT DISTINCT TYPE
          FROM XX_ETW.XX_DISL_CAR_SCALE
         WHERE TYPE IS NOT NULL
       );

CREATE OR REPLACE VIEW XX_ETW.ETW_CAR_NSI AS
SELECT *
  FROM XX_ETW.XX_DISL_ETW_CAR_NSI;

DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO l_count
    FROM USER_TABLES
   WHERE TABLE_NAME = 'SEND_TO_STATION_FORM_SAVE';

  IF l_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE XX_ETW.SEND_TO_STATION_FORM_SAVE (
        NAME             VARCHAR2(240),
        SENDING_TIME     VARCHAR2(100),
        ARRIVAL_TIME     VARCHAR2(100),
        REASON           VARCHAR2(4000),
        TRAIN_NUM        VARCHAR2(100),
        LOCO1_NUM        NUMBER,
        LOCO1_DRIVER1    NUMBER,
        LOCO1_DRIVER2    NUMBER,
        LOCO1_CONDUCTOR  NUMBER,
        LOCO2_NUM        NUMBER,
        LOCO2_DRIVER1    NUMBER,
        LOCO2_DRIVER2    NUMBER,
        LOCO2_CONDUCTOR  NUMBER,
        CARS             VARCHAR2(4000),
        CREATED_BY       NUMBER,
        CREATED_DATE     DATE,
        LAST_UPDATE_BY   NUMBER,
        LAST_UPDATE_DATE DATE
      )';
  END IF;
END;
/

CREATE OR REPLACE VIEW XX_ETW.XX_DISL_LOCO_ROUTES_V AS
SELECT lr.*,
       TO_CHAR(lr.ROUTE_ID) ROUTE_NUM,
       TO_CHAR(lr.STATUS) STATUS_DESC
  FROM XX_ETW.XX_DISL_LOCO_ROUTES lr;

CREATE OR REPLACE VIEW XX_ETW.XX_DISL_LOCO_ADD_FROM_OEBS_V AS
SELECT CAST(NULL AS NUMBER) INSTANCE_ID,
       CAST(NULL AS VARCHAR2(240)) INSTANCE_NUMBER,
       CAST(NULL AS VARCHAR2(240)) CATEGORY,
       CAST(NULL AS NUMBER) PAR_INSTANCE_ID,
       CAST(NULL AS VARCHAR2(240)) PAR_INSTANCE_NUMBER,
       CAST(NULL AS VARCHAR2(240)) DEPARTMENT_CODE
  FROM DUAL
 WHERE 1 = 0;

CREATE OR REPLACE VIEW XX_ETW.XX_DISL_FUEL_STANDART_V AS
SELECT fs.*,
       TO_CHAR(fs.BASE_TYPE) BASE_TYPE_DESCR,
       TO_CHAR(fs.INSTANCE_ID) INSTANCE_DESCR,
       TO_CHAR(fs.SEASON) SEASON_DESCR,
       TO_CHAR(fs.CONS_RATE_TYPE) CONS_RATE_TYPE_DESCR,
       TO_CHAR(fs.FUEL_TYPE) FUEL_TYPE_DESCR,
       TO_CHAR(fs.CREATED_BY) CREATED_BY_DESC,
       TO_CHAR(fs.LAST_UPDATE_BY) LAST_UPDATE_BY_DESC
  FROM XX_ETW.XX_DISL_FUEL_STANDART fs;

CREATE OR REPLACE VIEW XX_ETW.XX_DISL_SMENA_CHANGE_V AS
SELECT sc.SHIFT_CHANGE_ID,
       TO_CHAR(sc.SMENA_CHANGE_ID) SMENA_NUM,
       TO_CHAR(sc.STATUS_ID) STATUS_NAME,
       sc.STATUS_ID,
       sc.LAST_STATUS_ID,
       TO_CHAR(sc.CREATED_BY) CREATED_NAME,
       sc.CREATED_DATE,
       sc.LAST_UPDATE_DATE,
       st.SHORT_NAME STATION_SHORT_NAME,
       sc.STATION_ID,
       CAST(0 AS NUMBER) RAILWAYS_COUNT,
       CAST(0 AS NUMBER) PLACE_COUNT,
       CAST(0 AS NUMBER) INCORRECT_RAILWAYS,
       CAST(0 AS NUMBER) INCORRECT_PLACE,
       CAST(0 AS NUMBER) INCCORECT_TOTAL,
       sc.SIGN_OF_CHANGE,
       TO_CHAR(sc.SMENA_CHANGE_ID) SMENA_CHANGE,
       sc.SMENA_CHANGE_ID,
       sc.USER_CHANGE_ID,
       TO_CHAR(sc.USER_CHANGE_ID) USER_CHANGE,
       sc.DATE_CHANGE,
       sc.NOTE_CHANGE,
       sc.START_DATE_SHIFT,
       sc.DEV_CHANGE_TOTAL,
       sc.DEV_CHANGE_CORRECT,
       sc.DEV_CHANGE_INCCORECT,
       sc.SIGN_OF_RECEPTION,
       TO_CHAR(sc.USER_RECEPTION_ID) USER_RECEPTION,
       sc.DATE_RECEPTION,
       sc.SMENA_RECEPTION_ID,
       sc.DEV_RECEPTION_TOTAL,
       sc.DEV_RECEPTION_CORRECT,
       sc.DEV_RECEPTION_INCCORECT,
       sc.USER_RECEPTION_ID,
       sc.NOTE_RECEPTION,
       CAST(NULL AS VARCHAR2(4000)) L_MASS_SHORT_WAG
  FROM XX_ETW.XX_DISL_SHIFT_CHANGE sc
       LEFT JOIN XX_ETW.XX_DISL_STATIONS st ON st.STATION_ID = sc.STATION_ID;

CREATE OR REPLACE VIEW XX_ETW.XX_DISL_OPM_TRX_HEADER_V AS
SELECT h.*,
       TO_CHAR(h.CREATED_BY) CREATED_FIO,
       TO_CHAR(h.LAST_UPDATED_BY) LAST_UPDATED_FIO
  FROM XX_ETW.XX_DISL_OPM_TRX_HEADER h;

CREATE OR REPLACE VIEW XX_ETW.XX_DISL_FREIGHT_OEBS_V AS
SELECT f.*,
       TO_CHAR(f.ITEM_OEBS_ID) CODE_BASE
  FROM XX_ETW.XX_DISL_FREIGHT_OEBS f;
